services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:+dwCVCxSSLXfMdBxPIYlfjR1227WI6TGCWd8BP1AVNM=
      SESSION_DRIVER: file
      CACHE_STORE: file
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      WIREGUARD_USERNAME: username
      WIREGUARD_PASSWORD: api_password
      WIREGUARD_URL: http://77.73.132.31:8888/api/v1
      AUTH_TOKEN: 3f9777abfe54c8be9c39c05c1b11b7a9
    depends_on:
      - postgres
    networks:
      - laravel
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command: >
      sh -c "
        php artisan optimize:clear &&
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan l5-swagger:generate &&
        php artisan migrate --seed &&
        php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:15
    container_name: postgres_laravel_app
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
